name: Sync to Hugging Face

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Sync to Hugging Face
        uses: opentunes-ai/.github/workflows/sync-to-huggingface@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          huggingface_token: ${{ secrets.HF_TOKEN }}
          huggingface_repo: "bixoryai/opentunes-ai"
